name: Test

on:
  push:
    branches: [ master ]

jobs:
  go-test:
    name: go-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
        run: go get .
      - name: test
        run: go test -v ./...
